// front-end/nivel04/angular/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Livro } from '../livro';
import { Editora } from '../editora';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css'],
})
export class LivroDadosComponent implements OnInit {
  public livro!: Livro;
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];
  editora!: Editora[];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {}

  ngOnInit() {
    // this.servEditora.getEditoras().subscribe((editora: Array<Editora>) => {
    //   this.editora = editora;
    // });
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros.incluir(this.livro);
    this.servLivros.incluir(this.livro);
    this.router.navigateByUrl('/lista');
  };
}

<main class="container">
  <h2>Livros</h2>

  <form  ngNativeValidate>
    <div class="form-group">
      <label for="titulo">Título:</label>
      <input type="text" id="titulo" name="titulo" class="form-control" required [(ngModel)]="livro.titulo">
    </div>

    <div class="form-group">
      <label for="resumo">Resumo:</label>
      <textarea id="resumo" name="resumo" class="form-control" required [(ngModel)]="livro.resumo"></textarea>
    </div>

    <div class="form-group">
      <label for="editora">Editora:</label>
      <select id="editora" name="editora" class="form-control" required- [(ngModel)]="livro.codEditora">
        <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
      </select>
    </div>

    <div class="form-group">
      <label for="autores">Autores:</label>
      <textarea id="autores" name="autores" class="form-control" [(ngModel)]="autoresForm"></textarea>
    </div>

    <button type="submit" class="btn btn-primary" (click)="incluir()">Incluir</button>
  </form>
</main>

// front-end/nivel03/next-js/livros-react/src/LivroDados.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import controleLivro from './controle/ControleLivros'; 
import controleEditora from './controle/ControleEditora'; 

function LivroDados() {
    const [titulo, setTitulo] = useState('');
    const [resumo, setResumo] = useState('');
    const [autores, setAutores] = useState('');
    const [codEditora, setCodEditora] = useState(0);
    const navigate = useNavigate();

    const opcoes = controleEditora.getEditoras().map(editora => ({
        value: editora.codEditora,
        text: editora.nome
    }));

    const tratarCombo = (event) => {
        setCodEditora(Number(event.target.value));
    };

    const incluir = (event) => {
        event.preventDefault();

        const autoresArray = autores.split('\n').map(author => author.trim());

        const novoLivro = {
            codLivro: 0, 
            titulo,
            resumo,
            autores: autoresArray,
            codEditora
        };

        controleLivro.incluir(novoLivro);

        navigate('/');
    };

    return (
        <main>
            <h1>Dados do Livro</h1>
            <form class="form-horizontal" onSubmit={incluir}>
                <div className="form-group">
                    <label class="col-md-4 control-label" for="textinput">Título:</label>
                    <div class="col-md-12">
                        <input class="form-control input-md"
                            type="text"
                            value={titulo}
                            onChange={(event) => setTitulo(event.target.value)}
                        />
                    </div>
                </div>

                <div className="form-group">
                    <label class="col-md-4 control-label" for="textinput">Resumo:</label>
                    <div class="col-md-12">
                        <textarea class="form-control" id="textarea" name="textarea"
                            value={resumo}
                            onChange={(event) => setResumo(event.target.value)}
                        />
                    </div>
                </div>

                <div className="form-group">
                    <label class="col-md-4 control-label" for="textinput">Autores (um por linha):</label>
                    <div class="col-md-12">
                        <textarea class="form-control" id="textarea" name="textarea"
                            value={autores}
                            onChange={(event) => setAutores(event.target.value)}
                        />
                    </div>
                </div>

                <div className="form-group">
                    <label class="col-md-4 control-label" for="selectbasic">Editora:</label>
                    <div class="col-md-12">
                        <select id="selectbasic" name="selectbasic" class="form-control"
                            value={codEditora}
                            onChange={tratarCombo}
                        >
                            {opcoes.map(opcao => (
                                <option key={opcao.value} value={opcao.value}>
                                    {opcao.text}
                                </option>
                            ))}
                        </select>
                    </div>
                </div>
                <br/>
                <button type="submit" className="btn btn-primary">Salvar dados</button>
            </form>
        </main >
    );
    }

export default LivroDados;
